config/routes.rb
SimpleForum::Application.routes.draw do
  get "control_panel/list"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :replies

  resources :topics, :shallow => true do
    resources :replies
  end
  resources :forums, :shallow => true do
    resources :topics
  end
  

   root :to => "forums#index"

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  has_many :topics 
  validates :name, :presence => true
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  skip_before_filter :authorize, :only => [:index]
  skip_before_filter :admin_required, :only => [:index]
  # GET /forums
  # GET /forums.xml
  def index
    @forums = Forum.all
    @last_replies = {}
    @total_topics = {}
    @total_replies = {}
    @forums.each do |forum|
      topics_list = Topic.all(:conditions => [ "forum_id = ?", forum.id])      
      topics = []      
      topics_list.each do |t|
        topics << t.id
      end

      # Get last reply for each forum
      @last_replies[forum.id] = Reply.find(:first, :conditions => [ "topic_id IN (?)", topics], :joins => "left outer join users on users.id = replies.user_id", :select => "users.*, replies.*", :order => "created_at DESC")

      # Get total topics for each forum
      @total_topics[forum.id] = Topic.count(:conditions => ["forum_id = ?", forum.id])

      # Get total replies for each forum
      if topics != nil
        @total_replies[forum.id] = Reply.count(:conditions => ["topic_id IN (?)", topics])
      else
        @total_replies[forum.id] = 0
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @forums }
    end
  end

  # GET /forums/1
  # GET /forums/1.xml
  def show
    @forum = Forum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @forum }
    end
  end
  
  # GET /forums/new
  # GET /forums/new.xml
  def new
    @forum = Forum.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @forum }
    end
  end

  # GET /forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
  end

  # POST /forums
  # POST /forums.xml
  def create
    @forum = Forum.new(params[:forum])

    respond_to do |format|
      if @forum.save
        format.html { redirect_to(:controller => 'forums', :action => 'index', :notice => 'Forum was successfully created.') }
        format.xml  { render :xml => @forum, :status => :created, :location => @forum }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @forum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /forums/1
  # PUT /forums/1.xml
  def update
    @forum = Forum.find(params[:id])

    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to(@forum, :notice => 'Forum was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @forum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.xml
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to(forums_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<fieldset style="width:300px">
  <legend>New Forum</legend>
  <div>
    <label for="name" >Name:</label>
    <%= f.text_field :name %>
  </div>
  <div><%= f.submit %></div>
</fieldset>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<%= link_to 'New Forum', new_forum_path %>
<br/><br/>
<table width="100%">
  <thead>
    <tr>
      <th></th>
      <th>Forum</th>
      <th>Last Reply</th>
      <th>Topics</th>
      <th>Replies</th>
    </tr>
     <tr><th colspan="5">General</th></tr>
  </thead> 
<% @forums.each do |forum| %>
  <tr>
    <td>&nbsp;</td>
    <td><%= link_to forum.name, "/forums/#{forum.id}/topics" %></td>
    <% if @last_replies[forum.id] != nil %>
      <td>
          <%=  @last_replies[forum.id]['title'] %>
          <br />
          by <%= @last_replies[forum.id]['username']%>
          <br />
          <%= @last_replies[forum.id]['created_at'] %>
      </td>
    <% else %>
      <td>No Reply</td>
    <% end %>

    <% if @total_topics[forum.id] != 0 %>
      <td><%= @total_topics[forum.id] %></td>
    <% else %>
      <td>No Topic</td>
    <% end %>
    
    <% if @total_replies[forum.id] != 0 %>
      <td><%= @total_replies[forum.id] %></td>
    <% else %>
      <td>No Reply</td>
    <% end %>
  </tr>
<% end %>
</table>
<br />

app/views/forums/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @forum.name %>
</p>


<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>