config/routes.rb
SimpleForum::Application.routes.draw do
  get "control_panel/list"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :replies

  resources :topics, :shallow => true do
    resources :replies
  end
  resources :forums, :shallow => true do
    resources :topics
  end
  

   root :to => "forums#index"

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  validates :title, :content, :topic_id, :user_id, :presence => true
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_filter  :load_topic  
  skip_before_filter :authorize, :only => [:index]
  skip_before_filter :admin_required
  # GET /replies
  # GET /replies.xml
  def index
    # Get the current topic information
    @topic = Topic.find_by_id(params[:topic_id], :joins => "left outer join users on users.id = topics.user_id", :select => "users.*, topics.*")
    
    # Get the forum of current topic
    @forum = Forum.find(@topic.forum_id)

    # Get total posts for the user who is owner of the topic
    @users_and_total_posts = {}
    @users_and_total_posts[@topic.user_id] = User.find(@topic.user_id, :joins => "left outer join replies on replies.user_id = users.id", :select => "users.*, count(replies.id) as posts_count", :group => "users.id") 

    # Get replies of current topic
    @replies = Reply.find_all_by_topic_id(params[:topic_id])

    # Get total posts for the users who reply the topic    
    @replies.each do |reply|
      if @users_and_total_posts.has_key?(reply.user_id) == false 
        @users_and_total_posts[reply.user_id] = User.find(reply.user_id, :joins => "left outer join replies on replies.user_id = users.id", :select => "users.*, count(replies.id) as posts_count", :group => "users.id") 
      end
    end  
    
    # Update view
    @topic.update_attribute(:view, @topic.view + 1)

    respond_to do |format|
      format.html # findreplies.html.erb
      format.xml  { render :xml => @replies }
    end
  end

  # GET /replies/1
  # GET /replies/1.xml
  def show
    @reply = Reply.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reply }
    end
  end

  # GET /replies/new
  # GET /replies/new.xml
  def new
    @reply = Reply.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reply }
    end
  end

  # GET /replies/1/edit
  def edit
    @reply = Reply.find(params[:id])
  end

  # POST /replies
  # POST /replies.xml
  def create
    @reply = Reply.new(params[:reply])
    @reply.topic_id = params[:topic_id]
    respond_to do |format|
      @reply.user_id = session[:user_id]
      if @reply.save
        format.html { redirect_to "/topics/#{@reply.topic_id}/replies"}
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reply.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /replies/1
  # PUT /replies/1.xml
  def update
    @reply = Reply.find(params[:id])

    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        format.html { redirect_to(@reply, :notice => 'Reply was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reply.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.xml
  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to(replies_url) }
      format.xml  { head :ok }
    end
  end
  
  private 
    def load_topic
      @topic = Topic.find(params[:topic_id])
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for(@reply, @topic.replies.new, :url => topic_replies_path(:topic_id => @topic)) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset style="width:500px">
    <legend>New Reply</legend>    
    <div>
      <label for="title">Title:</label>
      <%= f.text_field :title, :value => "Re: #{@topic.title}", :readonly => 'true' %>
    </div>
    <div>
      <label for="content">Content:</label>
      <%= f.text_area :content, :size => "50x12"  %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
Forum >> <%= link_to @forum.name, "/forums/#{@topic.forum_id}/topics" %> >> <%= @topic.title %>
<br/><br/>
<%= link_to 'New Reply', new_topic_reply_url %>
<br />
<% i= 1 %>
<table width="100%">
  <tr>
    <td width="80%"><%= @topic.created_at %></td>
    <td width="20%">#<%= i %></td>
  </tr>
  <tr>
    <td><%= @topic.username %></td>
    <td>
      Join Date: <%= @topic.created_at %>
      <br/>
      Location: <%= @topic.location %>
      <br/>
      Posts: <%= @users_and_total_posts[@topic.user_id].posts_count if @users_and_total_posts[@topic.user_id] != nil %>
    </td>
  </tr>
  <tr>
    <td colspan="2"><%= @topic.title %></td>
  </tr>
  <tr>
    <td colspan="2"><%= @topic.content %></td>
  </tr>
</table>
<% i= 2 %>
<br />
<% @replies.each do |reply| %>
<table width="100%">
  <tr>
    <td width="80%"><%= reply.created_at %></td>
    <td width="20%">#<%= i %></td>
  </tr>
  <tr>
    <td><%= reply.user.username %></td>
    <td>
      Join Date: <%= reply.user.created_at %>
      <br/>
      Location: <%= reply.user.location %>
      <br/>
      Posts: <%= @users_and_total_posts[reply.user_id].posts_count %>
    </td>
  </tr>
  <tr>
    <td colspan="2"><%= reply.title %></td>
  </tr>
  <tr>
    <td colspan="2"><%= reply.content %></td>
  </tr>
</table>
<br/>
<% i += 1 %>
<% end %>

app/views/replies/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', topic_replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @reply.title %>
</p>

<p>
  <b>Content:</b>
  <%= @reply.content %>
</p>

<p>
  <b>Topic:</b>
  <%= @reply.topic_id %>
</p>

<p>
  <b>User:</b>
  <%= @reply.user_id %>
</p>


<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>