config/routes.rb
SimpleForum::Application.routes.draw do
  get "control_panel/list"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :replies

  resources :topics, :shallow => true do
    resources :replies
  end
  resources :forums, :shallow => true do
    resources :topics
  end
  

   root :to => "forums#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :replies
  has_one :user
  belongs_to :forum
  validates :title, :forum_id, :user_id, :view, :content, :presence => true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.xml
  before_filter  :load_forum
  skip_before_filter :authorize, :only => [:index]
  skip_before_filter :admin_required, :only => [:index]
  def index
    @forum = Forum.find(params[:forum_id])
    @topics = Topic.find_all_by_forum_id(params[:forum_id])  
    @last_replies = {}    
    @total_replies = {}
    @total_view = {}
    @topics.each do |topic|
      # Get last reply for each topic
      @last_replies[topic.id] = Reply.find(:first, :conditions => [ "topic_id = ?", topic.id], :order => "created_at DESC")    
    
      # Get total replies for each topic
      @total_replies[topic.id] = Reply.count(:conditions => [ "topic_id = ?", topic.id])    
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = Topic.new(params[:topic])
    @topic.user_id = session[:user_id]
    @topic.view = 0
    @topic.forum_id = params[:forum_id]  
    respond_to do |format|       
      if @topic.save
        format.html { redirect_to "/forums/#{@topic.forum_id.to_s}/topics"}
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end 

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(@topic, :notice => 'Topic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(topics_url) }
      format.xml  { head :ok }
    end
  end
  
  private 
    def load_forum
      @forum = Forum.find(params[:forum_id])
    end 
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic, @forum.topics.new, :url => forum_topics_path(:forum_id => @forum)) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>
      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset style="width:500px">
    <legend>New Topic</legend>
    <div>
      <label for="title">Title:</label>
      <%= f.text_field :title %>
    </div>

    <div>
      <label for="content">Content:</label>
      <%= f.text_area :content, :size => "50x12"  %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<%= link_to 'Forum', forums_url %> >> <%= @forum.name %>
<br /><br />
<%= link_to 'New Topic',  new_forum_topic_url %>
<br />
<table width="100%">
  <thead>
    <tr>
      <td colspan="5">Thread in Forum: <%= @forum.name %></td>
    </tr>
    <tr>
      <th></th>
      <th>Topic</th>
      <th>Last Reply</th>
      <th>Replies</th>
      <th>View</th>
    </tr>
  </thead>
<% @topics.each do |topic| %>
  <tr>
    <td></td>
    <td><%= link_to topic.title, "/topics/#{topic.id}/replies" %></td>
    <td><%= @last_replies[topic.id]['created_at'] if @last_replies[topic.id]!= nil %></td>
    <td><%= @total_replies[topic.id] != 0 ? @total_replies[topic.id] : "No Reply" %></td>
    <td><%= topic.view != 0 ? topic.view : "No View" %></td>
  </tr>
<% end %>
</table>

app/views/topics/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', forum_topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @topic.title %>
</p>

<p>
  <b>Forum:</b>
  <%= @topic.forum_id %>
</p>

<p>
  <b>User:</b>
  <%= @topic.user_id %>
</p>

<p>
  <b>View:</b>
  <%= @topic.view %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>