config/routes.rb
SimpleForum::Application.routes.draw do
  get "control_panel/list"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :replies

  resources :topics, :shallow => true do
    resources :replies
  end
  resources :forums, :shallow => true do
    resources :topics
  end
  

   root :to => "forums#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :replies 
  has_many :topics
  validates :username, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  validates :email, :location, :presence => true
  class << self
    def authenticate(username, password)
      if user = find_by_username(username)
        if user.password == password
          user
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, :only => [:index, :new]
  skip_before_filter :admin_required, :only => [:index, :new]
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset style="width:500px">
    <legend>New User</legend>
    <div>
      <%= f.label :username, 'UserName:' %>
      <%= f.text_field :username, :size => 40 %>
    </div>
    <div>
      <%= f.label :password, 'Password:' %>
      <%= f.password_field :password, :size => 40 %>
    </div>
    
    <div>
      <%= f.label :password_confirmation, 'Confirm:' %>
      <%= f.password_field :password_confirmation, :size => 40 %>
    </div>

    <div>
      <%= f.label :location, 'Location:' %>
      <%= f.text_field :location, :size => 40 %>
    </div>
    <div>
      <%= f.label :email, 'Email:' %>
      <%= f.text_field :email, :size => 40 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<h3>Listing users</h3>
<table width="100%">
  <thead>
    <tr>
      <th>Username</th>
      <th>Location</th>
      <th>Email</th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.location %></td>
    <td><%= user.email %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', forums_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Location:</b>
  <%= @user.location %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>